add genre addCategoryId, removeCategoryId and updateCategoriesId integration tests
devfullcycle/FC3-admin-catalogo-de-videos-typescript pull request #1
Opened 2023-04-13 23:51 UTC by celsopires1999

Acrescentei os testes de integração dos métodos addCategoryId, removeCategoryId e updateCategoriesId da entidade "genre".
Em função dos testes, tive que alterar a entidade também.
Há uma pequena correção no nome de variável no teste do faker.

2023-04-22 02:47 UTC, argentinaluiz requested changes

2023-04-22 02:47 UTC, argentinaluiz commented on src/@core/src/genre/domain/entities/genre.ts
> +    this.categories_id = categoriesId;
Podemos aplicar a validação de dados antes de realizar a atribuição sem usar o cloneDeep, exemplo:
```typescript
Genre.validate({
  ...this.props,
  categories_id: new Map(this.categories_id).set(categoryId.value, categoryId)
})
```
Um map pode ser criado através de outro map e neste caso criamos um novo map com os dados do antigo e adicionando o novo elemento para ser validado.

2023-04-22 02:47 UTC, argentinaluiz commented on src/@core/src/genre/domain/entities/genre.ts
> +    this.categories_id = categoriesId;
Podemos aplicar o mesmo conceito do `addCategoryId` também no `removeCategoryId`.

2023-04-25 00:34 UTC, celsopires1999 reviewed
Trocado o clone do lodash por new Map.

2023-04-25 00:34 UTC, celsopires1999 commented on src/@core/src/genre/domain/entities/genre.ts
> +    this.categories_id = categoriesId;
Precisamos do valor validado para atribuir à propriedade.
```suggestion
   addCategoryId(categoryId: CategoryId) {
    const categoriesId = new Map(this.categories_id).set(categoryId.value, categoryId);

    Genre.validate({
      ...this.props,
      categories_id: categoriesId,
    });

    this.categories_id = categoriesId;
  }
```

2023-04-25 00:34 UTC, celsopires1999 commented on src/@core/src/genre/domain/entities/genre.ts
> +    this.categories_id = categoriesId;
Precisamos do valor validado para atribuir à propriedade.
```suggestion
    removeCategoryId(categoryId: CategoryId) {
    const categoriesId = new Map(this.categories_id);
    categoriesId.delete(categoryId.value);

    Genre.validate({
      ...this.props,
      categories_id: categoriesId,
    });

    this.categories_id = categoriesId;
  }
```

2023-05-03 00:37 UTC, argentinaluiz approved these changes

2023-05-03 00:38 UTC, merged